### ISSUE TITLE
Proxy deployment

### ISSUE THREAD

**Issue by mporrato** [theforeman/foreman-operations-collection#17] opened 2021-02-01 17:11 UTC
## User story

As a foreman admin, I want to have a reusable ansible role (or set of roles) that I can use in my foreman infrastructure automation to deploy a new proxy.

## Acceptance criteria

Given a server with a suitable pre-deployed OS, when the role(s) is/are applied to the server, the server is added as a proxy to the existing foreman infrastructure. The role should work with both foreman and downstream products.

## Steps

To deploy a proxy, the steps are:

1. Register the proxy server to the foreman server
2. Enable required repositories
3. Install the foreman-proxy-content package
4. Generate the TLS certs tarball on foreman, either by generating certs signed by the foreman CA or by providing pre-generated certs signed by an external CA
5. Transfer the certs tarball to the proxy host
6. Run forman-installer with the katello scenario

Steps 1 and 2 can be performed using the rhsm role from the OASIS system collection.

Step 3 is trivial.

Steps 4 and 5 are partly covered by different existing works:
- The foreman-operations-collection.certificate_bundle (pending PR #14 ; only covers cert creation, not deployment)
- As pointed out in #10 , forklift's foreman_proxy_content already covers this

Step 6 is covered by the current installer role.

##### ISSUE TYPE
 - Feature Idea

**Comment by evgeni** [comment] 2021-02-01 18:10
this is a nicer-worded duplicate of https://github.com/theforeman/foreman-operations-collection/issues/10, right? :)

**Closed as completed** 2021-03-12 16:50 UTC
